name: Language Benchmark

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Delete Previous Results
      run: |
        rm -f results.md
        echo "Deleted previous results.md if it existed."

    - name: Initialize Results Markdown
      run: echo "# Benchmark Results\n\n| Optimization Level | Prime Computation (ms) | Insertion (ms) |\n|--------------------|-------------------------|----------------|\n" > results.md

    - name: Run C++ Benchmarks with Optimization Levels
      env:
        OPT_LEVEL: O0
      run: |
        g++ -O0 benchmark.cpp -o benchmark_O0
        OPT_LEVEL=O0 ./benchmark_O0
        echo "Completed benchmark for -O0"
        
        g++ -O2 benchmark.cpp -o benchmark_O2
        OPT_LEVEL=O2 ./benchmark_O2
        echo "Completed benchmark for -O2"
        
        g++ -O3 benchmark.cpp -o benchmark_O3
        OPT_LEVEL=O3 ./benchmark_O3
       
